### ISSUE TITLE
Add an optional volume point for persisting settings

### ISSUE THREAD

**Issue by jboesl** [dpadgett/ql-docker#2]
Currently I can change your settings but as soon as I remove the container all my settings are gone. Please provide a volume point that I can set for serverconfig, access.txt other files that one might want to change.

**Comment by dpadgett** [comment]
in my case i just commit the settings change to github.  that way the config is stored off server in case i lose the vm.  but you can do the volume mount yourself.  i tried putting it in the dockerfile but you can't:

Step 46 : VOLUME /home/quake/ql/baseq3/server.cfg /home/quake/.quakelive/30960/baseq3/access.txt
cannot mount volume over existing file, file exists /var/lib/docker/aufs/mnt/e23a78aba325bd6fb90eced205039e3c9bb2c2ba1decf44b13945440e41bf5af/home/quake/Steam/steamapps/common/Quake Live Dedicated Server/baseq3/server.cfg

it should work if you do it from commandline though, just add -v server.cfg:/home/quake/ql/baseq3/server.cfg (similar for access.txt)

**Comment by jboesl** [comment]
I'll try it that way.
I'm used to have one directory for my volume where all related files are stored but your suggestion should work, too.
